// WIFI 
#define CONFIG_MAROVER_WIFI_STA_MODE 0  //Connesct to your AP if 1, otherwise creates one

#define CONFIG_MAROVER_WIFI_SSID "YOUR_WIFI_SSID"
#define CONFIG_MAROVER_WIFI_PWD "YOUR_WIFI_PASSWORD"


#define CONFIG_MAROVER_AP_WIFI_SSID "esp32-sv"
#define CONFIG_MAROVER_AP_WIFI_PWD "qwer1234"


//QuickJS engine enabled
#define CONFIG_MAROVER_QUICK_JS 1

//WEB
#define CONFIG_MAROVER_WEB_PORT 80
#define CONFIG_MAROVER_WEB_STREAMING_PORT "80"
#define CONFIG_MAROVER_WEB_USER "admin"
#define CONFIG_MAROVER_WEB_PASSWORD "admin"


#define CONFIG_MAROVER_AXIS_NUMBER 2
#define CONFIG_MAROVER_CHANNELS_NUMBER 8


#define CHASIS_MODE_DUMMY 1
#define CHASIS_MODE_PWM 2
#define CONFIG_MAROVER_CHASIS_MODE CHASIS_MODE_PWM

#define CONFIG_MAROVER_CHASIS_IDLE_MS 1000